/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author SINGER
 */
public class Calculator extends javax.swing.JFrame {

    String firstValue;
    String operator = "";
    boolean dot;
    double memory;

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        display = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        mcBtn = new javax.swing.JButton();
        mrBtn = new javax.swing.JButton();
        msBtn = new javax.swing.JButton();
        mPlusBtn = new javax.swing.JButton();
        mSubstracTionBtn = new javax.swing.JButton();
        openBracketBtn = new javax.swing.JButton();
        closingBracketBtn = new javax.swing.JButton();
        ceBtn = new javax.swing.JButton();
        cBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        sevenBtn = new javax.swing.JButton();
        eightBtn = new javax.swing.JButton();
        nineBtn = new javax.swing.JButton();
        divideBtn = new javax.swing.JButton();
        oneOrxBtn = new javax.swing.JButton();
        fourBtn = new javax.swing.JButton();
        fiveBtn = new javax.swing.JButton();
        sixBtn = new javax.swing.JButton();
        multiplicationBtn = new javax.swing.JButton();
        percentageBtn = new javax.swing.JButton();
        oneBtn = new javax.swing.JButton();
        twoBtn = new javax.swing.JButton();
        threeBtn = new javax.swing.JButton();
        substractionBtn = new javax.swing.JButton();
        sqrtBtn = new javax.swing.JButton();
        dotBtn = new javax.swing.JButton();
        zeroBtn = new javax.swing.JButton();
        twoSqBtn = new javax.swing.JButton();
        plusBtn = new javax.swing.JButton();
        equalBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setBackground(new java.awt.Color(153, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 3, 3));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 0, -1, 50));

        display.setBackground(new java.awt.Color(51, 51, 51));
        display.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        display.setForeground(new java.awt.Color(255, 255, 255));
        display.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        display.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        display.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        display.setOpaque(true);
        display.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                displayAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 388, 70));

        jPanel2.setLayout(new java.awt.GridLayout(6, 5, 4, 4));

        mcBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mc.png"))); // NOI18N
        mcBtn.setContentAreaFilled(false);
        mcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcBtnActionPerformed(evt);
            }
        });
        jPanel2.add(mcBtn);

        mrBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mr.png"))); // NOI18N
        mrBtn.setContentAreaFilled(false);
        mrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrBtnActionPerformed(evt);
            }
        });
        jPanel2.add(mrBtn);

        msBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ms.png"))); // NOI18N
        msBtn.setContentAreaFilled(false);
        msBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msBtnActionPerformed(evt);
            }
        });
        jPanel2.add(msBtn);

        mPlusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mplus.png"))); // NOI18N
        mPlusBtn.setContentAreaFilled(false);
        mPlusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPlusBtnActionPerformed(evt);
            }
        });
        jPanel2.add(mPlusBtn);

        mSubstracTionBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mminus.png"))); // NOI18N
        mSubstracTionBtn.setContentAreaFilled(false);
        mSubstracTionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSubstracTionBtnActionPerformed(evt);
            }
        });
        jPanel2.add(mSubstracTionBtn);

        openBracketBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/openBracket.png"))); // NOI18N
        openBracketBtn.setContentAreaFilled(false);
        openBracketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBracketBtnActionPerformed(evt);
            }
        });
        jPanel2.add(openBracketBtn);

        closingBracketBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/closingBracket.png"))); // NOI18N
        closingBracketBtn.setContentAreaFilled(false);
        closingBracketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closingBracketBtnActionPerformed(evt);
            }
        });
        jPanel2.add(closingBracketBtn);

        ceBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ce.png"))); // NOI18N
        ceBtn.setContentAreaFilled(false);
        ceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ceBtn);

        cBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/c.png"))); // NOI18N
        cBtn.setContentAreaFilled(false);
        cBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBtnActionPerformed(evt);
            }
        });
        jPanel2.add(cBtn);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backspace.png"))); // NOI18N
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel2.add(backBtn);

        sevenBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/no7.png"))); // NOI18N
        sevenBtn.setContentAreaFilled(false);
        sevenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenBtnActionPerformed(evt);
            }
        });
        jPanel2.add(sevenBtn);

        eightBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/no8.png"))); // NOI18N
        eightBtn.setContentAreaFilled(false);
        eightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightBtnActionPerformed(evt);
            }
        });
        jPanel2.add(eightBtn);

        nineBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/no9.png"))); // NOI18N
        nineBtn.setContentAreaFilled(false);
        nineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineBtnActionPerformed(evt);
            }
        });
        jPanel2.add(nineBtn);

        divideBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/divide.png"))); // NOI18N
        divideBtn.setContentAreaFilled(false);
        divideBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideBtnActionPerformed(evt);
            }
        });
        jPanel2.add(divideBtn);

        oneOrxBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1nx.png"))); // NOI18N
        oneOrxBtn.setContentAreaFilled(false);
        oneOrxBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneOrxBtnActionPerformed(evt);
            }
        });
        jPanel2.add(oneOrxBtn);

        fourBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/no4.png"))); // NOI18N
        fourBtn.setContentAreaFilled(false);
        fourBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourBtnActionPerformed(evt);
            }
        });
        jPanel2.add(fourBtn);

        fiveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/no5.png"))); // NOI18N
        fiveBtn.setContentAreaFilled(false);
        fiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveBtnActionPerformed(evt);
            }
        });
        jPanel2.add(fiveBtn);

        sixBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/no6.png"))); // NOI18N
        sixBtn.setContentAreaFilled(false);
        sixBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixBtnActionPerformed(evt);
            }
        });
        jPanel2.add(sixBtn);

        multiplicationBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/multiplication.png"))); // NOI18N
        multiplicationBtn.setContentAreaFilled(false);
        multiplicationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicationBtnActionPerformed(evt);
            }
        });
        jPanel2.add(multiplicationBtn);

        percentageBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/percentage.png"))); // NOI18N
        percentageBtn.setContentAreaFilled(false);
        percentageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentageBtnActionPerformed(evt);
            }
        });
        jPanel2.add(percentageBtn);

        oneBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/no1.png"))); // NOI18N
        oneBtn.setContentAreaFilled(false);
        oneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneBtnActionPerformed(evt);
            }
        });
        jPanel2.add(oneBtn);

        twoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/no2.png"))); // NOI18N
        twoBtn.setContentAreaFilled(false);
        twoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoBtnActionPerformed(evt);
            }
        });
        jPanel2.add(twoBtn);

        threeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/no3.png"))); // NOI18N
        threeBtn.setContentAreaFilled(false);
        threeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeBtnActionPerformed(evt);
            }
        });
        jPanel2.add(threeBtn);

        substractionBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minus.png"))); // NOI18N
        substractionBtn.setContentAreaFilled(false);
        substractionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                substractionBtnActionPerformed(evt);
            }
        });
        jPanel2.add(substractionBtn);

        sqrtBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sqrt.png"))); // NOI18N
        sqrtBtn.setContentAreaFilled(false);
        sqrtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtBtnActionPerformed(evt);
            }
        });
        jPanel2.add(sqrtBtn);

        dotBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dot.png"))); // NOI18N
        dotBtn.setContentAreaFilled(false);
        dotBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotBtnActionPerformed(evt);
            }
        });
        jPanel2.add(dotBtn);

        zeroBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/no0.png"))); // NOI18N
        zeroBtn.setContentAreaFilled(false);
        zeroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroBtnActionPerformed(evt);
            }
        });
        jPanel2.add(zeroBtn);

        twoSqBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2sq.png"))); // NOI18N
        twoSqBtn.setContentAreaFilled(false);
        twoSqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoSqBtnActionPerformed(evt);
            }
        });
        jPanel2.add(twoSqBtn);

        plusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        plusBtn.setContentAreaFilled(false);
        plusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusBtnActionPerformed(evt);
            }
        });
        jPanel2.add(plusBtn);

        equalBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/equal.png"))); // NOI18N
        equalBtn.setContentAreaFilled(false);
        equalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalBtnActionPerformed(evt);
            }
        });
        jPanel2.add(equalBtn);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 77, 400, 450));

        jMenu1.setText("View");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Help");
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void displayAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_displayAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_displayAncestorAdded

    private void zeroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroBtnActionPerformed
        String value = display.getText();
        if (value.equals("0") == false) {
            value += "0";
            display.setText(value);
        }
    }//GEN-LAST:event_zeroBtnActionPerformed

    private void oneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneBtnActionPerformed
        display.setText(display.getText() + "1");
    }//GEN-LAST:event_oneBtnActionPerformed

    private void twoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoBtnActionPerformed
        display.setText(display.getText() + "2");
    }//GEN-LAST:event_twoBtnActionPerformed

    private void threeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeBtnActionPerformed
        display.setText(display.getText() + "3");
    }//GEN-LAST:event_threeBtnActionPerformed

    private void fourBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourBtnActionPerformed
        display.setText(display.getText() + "4");
    }//GEN-LAST:event_fourBtnActionPerformed

    private void fiveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveBtnActionPerformed
        display.setText(display.getText() + "5");
    }//GEN-LAST:event_fiveBtnActionPerformed

    private void sixBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixBtnActionPerformed
        display.setText(display.getText() + "6");
    }//GEN-LAST:event_sixBtnActionPerformed

    private void sevenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenBtnActionPerformed
        display.setText(display.getText() + "7");
    }//GEN-LAST:event_sevenBtnActionPerformed

    private void eightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightBtnActionPerformed
        display.setText(display.getText() + "8");
    }//GEN-LAST:event_eightBtnActionPerformed

    private void nineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineBtnActionPerformed
        display.setText(display.getText() + "9");
    }//GEN-LAST:event_nineBtnActionPerformed

    private void cBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBtnActionPerformed
        firstValue = "";
        operator = "";
        display.setText("");
    }//GEN-LAST:event_cBtnActionPerformed

    private void ceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceBtnActionPerformed
        display.setText("");
    }//GEN-LAST:event_ceBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        String value = display.getText();
        if (value.length() != 0) {
            value = value.substring(0, value.length() - 1);
            display.setText(value);
        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void dotBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotBtnActionPerformed
        if (dot == false && display.getText().isEmpty() == false) {
            String value = display.getText();
            display.setText(value + ".");
            dot = true;
        }
    }//GEN-LAST:event_dotBtnActionPerformed

    private void openBracketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBracketBtnActionPerformed
        display.setText(display.getText() + "(");
    }//GEN-LAST:event_openBracketBtnActionPerformed

    private void closingBracketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closingBracketBtnActionPerformed
        display.setText(display.getText() + ")");
    }//GEN-LAST:event_closingBracketBtnActionPerformed

    private void plusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusBtnActionPerformed
        firstValue = display.getText();
        operator = "+";
        display.setText("");
        dot = false;
    }//GEN-LAST:event_plusBtnActionPerformed

    private void substractionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_substractionBtnActionPerformed
        firstValue = display.getText();
        operator = "-";
        display.setText("");
        dot = false;
    }//GEN-LAST:event_substractionBtnActionPerformed

    private void multiplicationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicationBtnActionPerformed
        firstValue = display.getText();
        operator = "*";
        display.setText("");
        dot = false;
    }//GEN-LAST:event_multiplicationBtnActionPerformed

    private void divideBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideBtnActionPerformed
        firstValue = display.getText();
        operator = "/";
        display.setText("");
        dot = false;
    }//GEN-LAST:event_divideBtnActionPerformed

    private void equalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalBtnActionPerformed
        String secondValue = display.getText();
        if (secondValue.isEmpty() == false) {
            if (operator == "") {
                display.setText(secondValue);
            } else {
                double number1 = Double.parseDouble(firstValue);
                double number2 = Double.parseDouble(secondValue);
                double result = 0;
                switch (operator) {
                    case "+":
                        result = number1 + number2;
                        break;
                    case "-":
                        result = number1 - number2;
                        break;
                    case "*":
                        result = number1 * number2;
                        break;
                    case "/":
                        result = number1 / number2;
                        break;
                    case "%":
                        result = (number1 / 100) * number2;
                        break;
                }
                display.setText(String.valueOf(result));
            }
        }
    }//GEN-LAST:event_equalBtnActionPerformed

    private void oneOrxBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneOrxBtnActionPerformed
        String value = display.getText();
        if (value.isEmpty() == false) {
            double inverse = 1 / Double.parseDouble(value);
            display.setText(String.valueOf(inverse));
        }
    }//GEN-LAST:event_oneOrxBtnActionPerformed

    private void twoSqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoSqBtnActionPerformed
        String value = display.getText();
        if (value.isEmpty() == false) {
            double number = Double.parseDouble(value);
            double result = number * number;
            display.setText(String.valueOf(result));
        }
    }//GEN-LAST:event_twoSqBtnActionPerformed

    private void sqrtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtBtnActionPerformed
        String value = display.getText();
        double number = Double.parseDouble(value);

        double sqrt = Math.sqrt(number);
        display.setText(String.valueOf(sqrt));
    }//GEN-LAST:event_sqrtBtnActionPerformed

    private void mcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcBtnActionPerformed
        memory = 0;
    }//GEN-LAST:event_mcBtnActionPerformed

    private void mrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrBtnActionPerformed
        if (memory > 0) {
            display.setText(String.valueOf(memory));
        }
    }//GEN-LAST:event_mrBtnActionPerformed

    private void msBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msBtnActionPerformed
        String value = display.getText();
        if (value.isEmpty() == false) {
            double number = Double.parseDouble(value);
            if (number > 0) {
                memory = number;
            }
        }
    }//GEN-LAST:event_msBtnActionPerformed

    private void mPlusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPlusBtnActionPerformed
        String value = display.getText();
        if (value.isEmpty() == false) {
            memory = memory + Double.parseDouble(value);
            display.setText(String.valueOf(memory));
        }
    }//GEN-LAST:event_mPlusBtnActionPerformed

    private void mSubstracTionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSubstracTionBtnActionPerformed
        String value = display.getText();
        if (value.isEmpty() == false) {
            memory = memory - Double.parseDouble(value);
            display.setText(String.valueOf(memory));
        }
    }//GEN-LAST:event_mSubstracTionBtnActionPerformed

    private void percentageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentageBtnActionPerformed
        firstValue = display.getText();
        operator = "%";
        display.setText("");
        dot = false;
    }//GEN-LAST:event_percentageBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton cBtn;
    private javax.swing.JButton ceBtn;
    private javax.swing.JButton closingBracketBtn;
    private javax.swing.JLabel display;
    private javax.swing.JButton divideBtn;
    private javax.swing.JButton dotBtn;
    private javax.swing.JButton eightBtn;
    private javax.swing.JButton equalBtn;
    private javax.swing.JButton fiveBtn;
    private javax.swing.JButton fourBtn;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mPlusBtn;
    private javax.swing.JButton mSubstracTionBtn;
    private javax.swing.JButton mcBtn;
    private javax.swing.JButton mrBtn;
    private javax.swing.JButton msBtn;
    private javax.swing.JButton multiplicationBtn;
    private javax.swing.JButton nineBtn;
    private javax.swing.JButton oneBtn;
    private javax.swing.JButton oneOrxBtn;
    private javax.swing.JButton openBracketBtn;
    private javax.swing.JButton percentageBtn;
    private javax.swing.JButton plusBtn;
    private javax.swing.JButton sevenBtn;
    private javax.swing.JButton sixBtn;
    private javax.swing.JButton sqrtBtn;
    private javax.swing.JButton substractionBtn;
    private javax.swing.JButton threeBtn;
    private javax.swing.JButton twoBtn;
    private javax.swing.JButton twoSqBtn;
    private javax.swing.JButton zeroBtn;
    // End of variables declaration//GEN-END:variables
}
